version: "3.8"

services:
  triton:
    container_name: triton-resnet152
    image: nvcr.io/nvidia/tritonserver:24.10-py3
    ports:
      - 8000:8000 # HTTP API
      - 8001:8001 # gRPC API
      - 8002:8002 # Metrics Monitoring
    restart: always
    volumes:
      - ./triton/models:/models
    command: ["tritonserver", "--model-store=/models"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  trtexec_container:
    container_name: trtexec_container_triton-resnet152
    image: nvcr.io/nvidia/tensorrt:24.10-py3
    volumes:
      - ./trtexec_workspace:/workspace
    command: ["tail", "-f", "/dev/null"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
              driver: nvidia
